function [F, J, domerr] = mcp_funjac_multiple_convex_contact_patches_2(z, jacflag)

% initialize
z = z(:);
F = [];
J = [];
domerr = 0;

% obtain variable values
global h;

global q_old ;
q_xo = q_old(1);
q_yo = q_old(2);
q_zo = q_old(3);
q0_o = q_old(4);
q1_o = q_old(5);
q2_o = q_old(6);
q3_o = q_old(7);

global nu_old;
v_xo =nu_old(1);
v_yo =nu_old(2);
v_zo =nu_old(3);
w_xo =nu_old(4);
w_yo =nu_old(5);
w_zo =nu_old(6);

global m mu I_xx I_yy I_zz e_o e_t g Height r_s r_b;

global p_x p_y p_z p_xt p_yt p_zt;

% state vector
v_x = z(1);
v_y = z(2);
v_z=  z(3);
w_x = z(4);
w_y = z(5);
w_z = z(6);

a11_x = z(7);
a11_y = z(8);
a11_z = z(9);

a12_x = z(10);
a12_y = z(11);
a12_z = z(12);

a21_x = z(13);
a21_y = z(14);
a21_z = z(15);

a22_x = z(16);
a22_y = z(17);
a22_z = z(18);

p1_t = z(19);
p1_o = z(20);

p2_t = z(21);
p2_o = z(22);

sig1 = z(23);
sig2 = z(24);

l11 = z(25);
l12 = z(26);
l13 = z(27);

l21 = z(28);
l22 = z(29);
l23 = z(30);

p1_n = z(31);
p2_n = z(32);


% intermediate variables

q0 = -(2*((h*q1_o*w_x)/2 - q0_o + (h*q2_o*w_y)/2 + (h*q3_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q1 = (2*(q1_o + (h*q0_o*w_x)/2 + (h*q3_o*w_y)/2 - (h*q2_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q2 = (2*(q2_o - (h*q3_o*w_x)/2 + (h*q0_o*w_y)/2 + (h*q1_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q3 = (2*(q3_o + (h*q2_o*w_x)/2 - (h*q1_o*w_y)/2 + (h*q0_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);

q_x = q_xo+h*v_x;
q_y = q_yo+h*v_y;
q_z = q_zo+h*v_z;

R11 = q0^2 + q1^2 - q2^2 - q3^2;
R12 = 2*q1*q2 - 2*q0*q3;
R13 = 2*q0*q2 + 2*q1*q3;
R21 = 2*q0*q3 + 2*q1*q2;
R22 = q0^2 - q1^2 + q2^2 - q3^2;
R23 = 2*q2*q3 - 2*q0*q1;
R31 = 2*q1*q3 - 2*q0*q2;
R32 = 2*q0*q1 + 2*q2*q3;
R33 = q0^2 - q1^2 - q2^2 + q3^2;

% simplifaction variables
r1_x = R11*a11_x + R21*a11_y + R31*a11_z - R11*q_x - R21*q_y - R31*q_z;
r1_y = R12*a11_x + R22*a11_y + R32*a11_z - R12*q_x - R22*q_y - R32*q_z;
r2_x = R11*a21_x + R21*a21_y + R31*a21_z - R11*q_x - R21*q_y - R31*q_z;
r2_y = R12*a21_x + R22*a21_y + R32*a21_z - R12*q_x - R22*q_y - R32*q_z;

v1_t = e_t^2*mu*v_x - e_t^2*mu*w_z*(a11_y - q_y) + e_t^2*mu*w_y*(a11_z - q_z);
v1_o = e_o^2*mu*v_y + e_o^2*mu*w_z*(a11_x - q_x) - e_o^2*mu*w_x*(a11_z - q_z);
v2_t = e_t^2*mu*v_x - e_t^2*mu*w_z*(a21_y - q_y) + e_t^2*mu*w_y*(a21_z - q_z);
v2_o = e_o^2*mu*v_y + e_o^2*mu*w_z*(a21_x - q_x) - e_o^2*mu*w_x*(a21_z - q_z);

I11 = (I_xx*R11^2 + I_yy*R12^2 + I_zz*R13^2);
I12 = (I_xx*R11*R21 + I_yy*R12*R22 + I_zz*R13*R23);
I13 = (I_xx*R11*R31 + I_yy*R12*R32 + I_zz*R13*R33);
%I21 = I12;
I22 = (I_xx*R21^2 + I_yy*R22^2 + I_zz*R23^2);
I23 = (I_xx*R21*R31 + I_yy*R22*R32 + I_zz*R23*R33);
%I31 = I13;
%I32 = I23;
I33 = (I_xx*R31^2 + I_yy*R32^2 + I_zz*R33^2);
w_s = (h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(3/2);
%%
F(1) = p1_t + p2_t  + p_x - m*(v_x - v_xo);
F(2) = p1_o + p2_o + p_y - m*(v_y - v_yo);
F(3) = p1_n + p2_n + p_z - m*(v_z - v_zo) - g*h*m;

F(4) = p_xt - p1_o*(a11_z - q_z) - p2_o*(a21_z - q_z) + p1_n*(a11_y - q_y) + p2_n*(a21_y - q_y) - h*(w_yo*(I13*w_xo + I23*w_yo + I33*w_zo) - w_zo*(I12*w_xo + I22*w_yo + I23*w_zo)) - I11*(w_x - w_xo) - I12*(w_y - w_yo) - I13*(w_z - w_zo);
F(5) = p_yt - p1_n*(a11_x - q_x) - p2_n*(a21_x - q_x) + p1_t*(a11_z - q_z) + p2_t*(a21_z - q_z)+ h*(w_xo*(I13*w_xo + I23*w_yo + I33*w_zo) - w_zo*(I11*w_xo + I12*w_yo + I13*w_zo)) - I12*(w_x - w_xo) - I22*(w_y - w_yo) - I23*(w_z - w_zo);
F(6) = p_zt + p1_o*(a11_x - q_x) + p2_o*(a21_x - q_x) - p1_t*(a11_y - q_y) - p2_t*(a21_y - q_y) - h*(w_xo*(I12*w_xo + I22*w_yo + I23*w_zo) - w_yo*(I11*w_xo + I12*w_yo + I13*w_zo)) - I13*(w_x - w_xo) - I23*(w_y - w_yo) - I33*(w_z - w_zo);

F(7) = mu*p1_n*(v_x - 2*w_z*(a11_y - q_y) + w_y*(a11_z - q_z))*e_t^2 + p1_t*sig1;
F(8) =  mu*p1_n*(v_y + 2*w_z*(a11_x - q_x) - w_x*(a11_z - q_z))*e_o^2 + p1_o*sig1;

F(9) = mu*p2_n*(v_x - 2*w_z*(a21_y - q_y) + w_y*(a21_z - q_z))*e_t^2 + p2_t*sig2;
F(10) = mu*p2_n*(v_y + 2*w_z*(a21_x - q_x) - w_x*(a21_z - q_z))*e_o^2 + p2_o*sig2;

F(11) = a12_x - a11_x;
F(12) = a12_y - a11_y;
F(13) = a12_z - a11_z + l13;

F(14) = l12*(2*R12*r1_y + 2*R11*(r1_x + r_b)) - R13*l11;
F(15) = l12*(2*R22*r1_y + 2*R21*(r1_x + r_b)) - R23*l11;
F(16) = l12*(2*R32*r1_y + 2*R31*(r1_x + r_b)) - R33*l11 + 1;

F(17) = a22_x - a21_x;
F(18) = a22_y - a21_y;
F(19) = a22_z - a21_z + l23;

F(20) = l22*(2*R12*r2_y + 2*R11*(r2_x - r_b)) - R13*l21;
F(21) = l22*(2*R22*r2_y + 2*R21*(r2_x - r_b)) - R23*l21;
F(22) = l22*(2*R32*r2_y + 2*R31*(r2_x - r_b)) - R33*l21 + 1;

F(23) = mu^2*p1_n^2  - p1_t^2/e_t^2 - p1_o^2/e_o^2;
F(24) = mu^2*p2_n^2  - p2_t^2/e_t^2 - p2_o^2/e_o^2;

F(25) =Height + R13*a11_x + R23*a11_y + R33*a11_z - R13*q_x - R23*q_y - R33*q_z;
F(26) = r_s^2 - r1_y^2 - (r1_x + r_b)^2;
F(27) = -a12_z;

F(28) =  Height + R13*a21_x + R23*a21_y + R33*a21_z - R13*q_x - R23*q_y - R33*q_z;
F(29) = r_s^2 - r2_y^2 - (r2_x - r_b)^2;
F(30) = -a22_z;

F(31) = a11_z;
F(32) = a21_z;

if (jacflag)
    J1 = [            -m,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               1,               0,               1,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,            -m,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               1,               0,               1,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0, -m,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        1,                                                        1,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,       - I_xx*R11^2 - I_yy*R12^2 - I_zz*R13^2, - I_xx*R11*R21 - I_yy*R12*R22 - I_zz*R13*R23, - I_xx*R11*R31 - I_yy*R12*R32 - I_zz*R13*R33,                                 0,                              p1_n,                             -p1_o, 0, 0,  0,                                 0,                              p2_n,                             -p2_o, 0, 0,  0,               0,     q_z - a11_z,               0,     q_z - a21_z,    0,    0,    0,                               0, 0,    0,                               0, 0,                                              a11_y - q_y,                                              a21_y - q_y, - h*(I_xx*R31*w_xo*w_yo - I_xx*R21*w_xo*w_zo) - 2*I_xx*R11*(w_x - w_xo) - I_xx*R21*(w_y - w_yo) - I_xx*R31*(w_z - w_zo), - h*(I_yy*R32*w_xo*w_yo - I_yy*R22*w_xo*w_zo) - 2*I_yy*R12*(w_x - w_xo) - I_yy*R22*(w_y - w_yo) - I_yy*R32*(w_z - w_zo), - h*(I_zz*R33*w_xo*w_yo - I_zz*R23*w_xo*w_zo) - 2*I_zz*R13*(w_x - w_xo) - I_zz*R23*(w_y - w_yo) - I_zz*R33*(w_z - w_zo),                  h*(w_zo*(I_xx*R11*w_xo + 2*I_xx*R21*w_yo + I_xx*R31*w_zo) - I_xx*R31*w_yo^2) - I_xx*R11*(w_y - w_yo),                  h*(w_zo*(I_yy*R12*w_xo + 2*I_yy*R22*w_yo + I_yy*R32*w_zo) - I_yy*R32*w_yo^2) - I_yy*R12*(w_y - w_yo),                  h*(w_zo*(I_zz*R13*w_xo + 2*I_zz*R23*w_yo + I_zz*R33*w_zo) - I_zz*R33*w_yo^2) - I_zz*R13*(w_y - w_yo),                  - h*(w_yo*(I_xx*R11*w_xo + I_xx*R21*w_yo + 2*I_xx*R31*w_zo) - I_xx*R21*w_zo^2) - I_xx*R11*(w_z - w_zo),                  - h*(w_yo*(I_yy*R12*w_xo + I_yy*R22*w_yo + 2*I_yy*R32*w_zo) - I_yy*R22*w_zo^2) - I_yy*R12*(w_z - w_zo),                  - h*(w_yo*(I_zz*R13*w_xo + I_zz*R23*w_yo + 2*I_zz*R33*w_zo) - I_zz*R23*w_zo^2) - I_zz*R13*(w_z - w_zo),                               0,                   - p1_n - p2_n,                     p1_o + p2_o
                       0,             0,  0, - I_xx*R11*R21 - I_yy*R12*R22 - I_zz*R13*R23,       - I_xx*R21^2 - I_yy*R22^2 - I_zz*R23^2, - I_xx*R21*R31 - I_yy*R22*R32 - I_zz*R23*R33,                             -p1_n,                                 0,                              p1_t, 0, 0,  0,                             -p2_n,                                 0,                              p2_t, 0, 0,  0,     a11_z - q_z,               0,     a21_z - q_z,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                              q_x - a11_x,                                              q_x - a21_x,                  - h*(w_zo*(2*I_xx*R11*w_xo + I_xx*R21*w_yo + I_xx*R31*w_zo) - I_xx*R31*w_xo^2) - I_xx*R21*(w_x - w_xo),                  - h*(w_zo*(2*I_yy*R12*w_xo + I_yy*R22*w_yo + I_yy*R32*w_zo) - I_yy*R32*w_xo^2) - I_yy*R22*(w_x - w_xo),                  - h*(w_zo*(2*I_zz*R13*w_xo + I_zz*R23*w_yo + I_zz*R33*w_zo) - I_zz*R33*w_xo^2) - I_zz*R23*(w_x - w_xo), h*(I_xx*R31*w_xo*w_yo - I_xx*R11*w_yo*w_zo) - I_xx*R11*(w_x - w_xo) - 2*I_xx*R21*(w_y - w_yo) - I_xx*R31*(w_z - w_zo), h*(I_yy*R32*w_xo*w_yo - I_yy*R12*w_yo*w_zo) - I_yy*R12*(w_x - w_xo) - 2*I_yy*R22*(w_y - w_yo) - I_yy*R32*(w_z - w_zo), h*(I_zz*R33*w_xo*w_yo - I_zz*R13*w_yo*w_zo) - I_zz*R13*(w_x - w_xo) - 2*I_zz*R23*(w_y - w_yo) - I_zz*R33*(w_z - w_zo),                    h*(w_xo*(I_xx*R11*w_xo + I_xx*R21*w_yo + 2*I_xx*R31*w_zo) - I_xx*R11*w_zo^2) - I_xx*R21*(w_z - w_zo),                    h*(w_xo*(I_yy*R12*w_xo + I_yy*R22*w_yo + 2*I_yy*R32*w_zo) - I_yy*R12*w_zo^2) - I_yy*R22*(w_z - w_zo),                    h*(w_xo*(I_zz*R13*w_xo + I_zz*R23*w_yo + 2*I_zz*R33*w_zo) - I_zz*R13*w_zo^2) - I_zz*R23*(w_z - w_zo),                     p1_n + p2_n,                               0,                   - p1_t - p2_t
                       0,             0,  0, - I_xx*R11*R31 - I_yy*R12*R32 - I_zz*R13*R33, - I_xx*R21*R31 - I_yy*R22*R32 - I_zz*R23*R33,       - I_xx*R31^2 - I_yy*R32^2 - I_zz*R33^2,                              p1_o,                             -p1_t,                                 0, 0, 0,  0,                              p2_o,                             -p2_t,                                 0, 0, 0,  0,     q_y - a11_y,     a11_x - q_x,     q_y - a21_y,     a21_x - q_x,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                    h*(w_yo*(2*I_xx*R11*w_xo + I_xx*R21*w_yo + I_xx*R31*w_zo) - I_xx*R21*w_xo^2) - I_xx*R31*(w_x - w_xo),                    h*(w_yo*(2*I_yy*R12*w_xo + I_yy*R22*w_yo + I_yy*R32*w_zo) - I_yy*R22*w_xo^2) - I_yy*R32*(w_x - w_xo),                    h*(w_yo*(2*I_zz*R13*w_xo + I_zz*R23*w_yo + I_zz*R33*w_zo) - I_zz*R23*w_xo^2) - I_zz*R33*(w_x - w_xo),                - h*(w_xo*(I_xx*R11*w_xo + 2*I_xx*R21*w_yo + I_xx*R31*w_zo) - I_xx*R11*w_yo^2) - I_xx*R31*(w_y - w_yo),                - h*(w_xo*(I_yy*R12*w_xo + 2*I_yy*R22*w_yo + I_yy*R32*w_zo) - I_yy*R12*w_yo^2) - I_yy*R32*(w_y - w_yo),                - h*(w_xo*(I_zz*R13*w_xo + 2*I_zz*R23*w_yo + I_zz*R33*w_zo) - I_zz*R13*w_yo^2) - I_zz*R33*(w_y - w_yo), - h*(I_xx*R21*w_xo*w_zo - I_xx*R11*w_yo*w_zo) - I_xx*R11*(w_x - w_xo) - I_xx*R21*(w_y - w_yo) - 2*I_xx*R31*(w_z - w_zo), - h*(I_yy*R22*w_xo*w_zo - I_yy*R12*w_yo*w_zo) - I_yy*R12*(w_x - w_xo) - I_yy*R22*(w_y - w_yo) - 2*I_yy*R32*(w_z - w_zo), - h*(I_zz*R23*w_xo*w_zo - I_zz*R13*w_yo*w_zo) - I_zz*R13*(w_x - w_xo) - I_zz*R23*(w_y - w_yo) - 2*I_zz*R33*(w_z - w_zo),                   - p1_o - p2_o,                     p1_t + p2_t,                               0
           e_t^2*mu*p1_n,             0,  0,                                            0,                  e_t^2*mu*p1_n*(a11_z - q_z),             -e_t^2*mu*p1_n*(2*a11_y - 2*q_y),                                 0,              -2*e_t^2*mu*p1_n*w_z,                 e_t^2*mu*p1_n*w_y, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,            sig1,               0,               0,               0, p1_t,    0,    0,                               0, 0,    0,                               0, 0, e_t^2*mu*(v_x - 2*w_z*(a11_y - q_y) + w_y*(a11_z - q_z)),                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,             2*e_t^2*mu*p1_n*w_z,              -e_t^2*mu*p1_n*w_y
                       0, e_o^2*mu*p1_n,  0,                 -e_o^2*mu*p1_n*(a11_z - q_z),                                            0,              e_o^2*mu*p1_n*(2*a11_x - 2*q_x),               2*e_o^2*mu*p1_n*w_z,                                 0,                -e_o^2*mu*p1_n*w_x, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,            sig1,               0,               0, p1_o,    0,    0,                               0, 0,    0,                               0, 0, e_o^2*mu*(v_y + 2*w_z*(a11_x - q_x) - w_x*(a11_z - q_z)),                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,            -2*e_o^2*mu*p1_n*w_z,                               0,               e_o^2*mu*p1_n*w_x
           e_t^2*mu*p2_n,             0,  0,                                            0,                  e_t^2*mu*p2_n*(a21_z - q_z),             -e_t^2*mu*p2_n*(2*a21_y - 2*q_y),                                 0,                                 0,                                 0, 0, 0,  0,                                 0,              -2*e_t^2*mu*p2_n*w_z,                 e_t^2*mu*p2_n*w_y, 0, 0,  0,               0,               0,            sig2,               0,    0, p2_t,    0,                               0, 0,    0,                               0, 0,                                                        0, e_t^2*mu*(v_x - 2*w_z*(a21_y - q_y) + w_y*(a21_z - q_z)),                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,             2*e_t^2*mu*p2_n*w_z,              -e_t^2*mu*p2_n*w_y
                       0, e_o^2*mu*p2_n,  0,                 -e_o^2*mu*p2_n*(a21_z - q_z),                                            0,              e_o^2*mu*p2_n*(2*a21_x - 2*q_x),                                 0,                                 0,                                 0, 0, 0,  0,               2*e_o^2*mu*p2_n*w_z,                                 0,                -e_o^2*mu*p2_n*w_x, 0, 0,  0,               0,               0,               0,            sig2,    0, p2_o,    0,                               0, 0,    0,                               0, 0,                                                        0, e_o^2*mu*(v_y + 2*w_z*(a21_x - q_x) - w_x*(a21_z - q_z)),                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,            -2*e_o^2*mu*p2_n*w_z,                               0,               e_o^2*mu*p2_n*w_x
                       0,             0,  0,                                            0,                                            0,                                            0,                                -1,                                 0,                                 0, 1, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                -1,                                 0, 0, 1,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                -1, 0, 0,  1,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 1,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,           l12*(2*R11^2 + 2*R12^2),       l12*(2*R11*R21 + 2*R12*R22),       l12*(2*R11*R31 + 2*R12*R32), 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0, -R13, 2*R12*r1_y + 2*R11*(r1_x + r_b), 0,    0,                               0, 0,                                                        0,                                                        0,                                                                              l12*(2*r1_x + 2*r_b + 2*R11*(a11_x - q_x)),                                                                                      l12*(2*r1_y + 2*R12*(a11_x - q_x)),                                                                                                                    -l11,                                                                                               2*R11*l12*(a11_y - q_y),                                                                                               2*R12*l12*(a11_y - q_y),                                                                                                                     0,                                                                                                 2*R11*l12*(a11_z - q_z),                                                                                                 2*R12*l12*(a11_z - q_z),                                                                                                                       0,        -l12*(2*R11^2 + 2*R12^2),    -l12*(2*R11*R21 + 2*R12*R22),    -l12*(2*R11*R31 + 2*R12*R32)
                       0,             0,  0,                                            0,                                            0,                                            0,       l12*(2*R11*R21 + 2*R12*R22),           l12*(2*R21^2 + 2*R22^2),       l12*(2*R21*R31 + 2*R22*R32), 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0, -R23, 2*R22*r1_y + 2*R21*(r1_x + r_b), 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                 2*R21*l12*(a11_x - q_x),                                                                                                 2*R22*l12*(a11_x - q_x),                                                                                                                       0,                                                                            l12*(2*r1_x + 2*r_b + 2*R21*(a11_y - q_y)),                                                                                    l12*(2*r1_y + 2*R22*(a11_y - q_y)),                                                                                                                  -l11,                                                                                                 2*R21*l12*(a11_z - q_z),                                                                                                 2*R22*l12*(a11_z - q_z),                                                                                                                       0,    -l12*(2*R11*R21 + 2*R12*R22),        -l12*(2*R21^2 + 2*R22^2),    -l12*(2*R21*R31 + 2*R22*R32)
                       0,             0,  0,                                            0,                                            0,                                            0,       l12*(2*R11*R31 + 2*R12*R32),       l12*(2*R21*R31 + 2*R22*R32),           l12*(2*R31^2 + 2*R32^2), 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0, -R33, 2*R32*r1_y + 2*R31*(r1_x + r_b), 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                 2*R31*l12*(a11_x - q_x),                                                                                                 2*R32*l12*(a11_x - q_x),                                                                                                                       0,                                                                                               2*R31*l12*(a11_y - q_y),                                                                                               2*R32*l12*(a11_y - q_y),                                                                                                                     0,                                                                              l12*(2*r1_x + 2*r_b + 2*R31*(a11_z - q_z)),                                                                                      l12*(2*r1_y + 2*R32*(a11_z - q_z)),                                                                                                                    -l11,    -l12*(2*R11*R31 + 2*R12*R32),    -l12*(2*R21*R31 + 2*R22*R32),        -l12*(2*R31^2 + 2*R32^2)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                -1,                                 0,                                 0, 1, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                -1,                                 0, 0, 1,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                -1, 0, 0,  1,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 1,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,           l22*(2*R11^2 + 2*R12^2),       l22*(2*R11*R21 + 2*R12*R22),       l22*(2*R11*R31 + 2*R12*R32), 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0, -R13, 2*R12*r2_y + 2*R11*(r2_x - r_b), 0,                                                        0,                                                        0,                                                                              l22*(2*r2_x - 2*r_b + 2*R11*(a21_x - q_x)),                                                                                      l22*(2*r2_y + 2*R12*(a21_x - q_x)),                                                                                                                    -l21,                                                                                               2*R11*l22*(a21_y - q_y),                                                                                               2*R12*l22*(a21_y - q_y),                                                                                                                     0,                                                                                                 2*R11*l22*(a21_z - q_z),                                                                                                 2*R12*l22*(a21_z - q_z),                                                                                                                       0,        -l22*(2*R11^2 + 2*R12^2),    -l22*(2*R11*R21 + 2*R12*R22),    -l22*(2*R11*R31 + 2*R12*R32)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,       l22*(2*R11*R21 + 2*R12*R22),           l22*(2*R21^2 + 2*R22^2),       l22*(2*R21*R31 + 2*R22*R32), 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0, -R23, 2*R22*r2_y + 2*R21*(r2_x - r_b), 0,                                                        0,                                                        0,                                                                                                 2*R21*l22*(a21_x - q_x),                                                                                                 2*R22*l22*(a21_x - q_x),                                                                                                                       0,                                                                            l22*(2*r2_x - 2*r_b + 2*R21*(a21_y - q_y)),                                                                                    l22*(2*r2_y + 2*R22*(a21_y - q_y)),                                                                                                                  -l21,                                                                                                 2*R21*l22*(a21_z - q_z),                                                                                                 2*R22*l22*(a21_z - q_z),                                                                                                                       0,    -l22*(2*R11*R21 + 2*R12*R22),        -l22*(2*R21^2 + 2*R22^2),    -l22*(2*R21*R31 + 2*R22*R32)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,       l22*(2*R11*R31 + 2*R12*R32),       l22*(2*R21*R31 + 2*R22*R32),           l22*(2*R31^2 + 2*R32^2), 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0, -R33, 2*R32*r2_y + 2*R31*(r2_x - r_b), 0,                                                        0,                                                        0,                                                                                                 2*R31*l22*(a21_x - q_x),                                                                                                 2*R32*l22*(a21_x - q_x),                                                                                                                       0,                                                                                               2*R31*l22*(a21_y - q_y),                                                                                               2*R32*l22*(a21_y - q_y),                                                                                                                     0,                                                                              l22*(2*r2_x - 2*r_b + 2*R31*(a21_z - q_z)),                                                                                      l22*(2*r2_y + 2*R32*(a21_z - q_z)),                                                                                                                    -l21,    -l22*(2*R11*R31 + 2*R12*R32),    -l22*(2*R21*R31 + 2*R22*R32),        -l22*(2*R31^2 + 2*R32^2)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0, -(2*p1_t)/e_t^2, -(2*p1_o)/e_o^2,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                              2*mu^2*p1_n,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0, -(2*p2_t)/e_t^2, -(2*p2_o)/e_o^2,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                              2*mu^2*p2_n,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                               R13,                               R23,                               R33, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                             a11_x - q_x,                                                                                                                     0,                                                                                                                     0,                                                                                                           a11_y - q_y,                                                                                                                       0,                                                                                                                       0,                                                                                                             a11_z - q_z,                            -R13,                            -R23,                            -R33
                       0,             0,  0,                                            0,                                            0,                                            0, - 2*R12*r1_y - 2*R11*(r1_x + r_b), - 2*R22*r1_y - 2*R21*(r1_x + r_b), - 2*R32*r1_y - 2*R31*(r1_x + r_b), 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                           -2*(r1_x + r_b)*(a11_x - q_x),                                                                                                   -2*r1_y*(a11_x - q_x),                                                                                                                       0,                                                                                         -2*(r1_x + r_b)*(a11_y - q_y),                                                                                                 -2*r1_y*(a11_y - q_y),                                                                                                                     0,                                                                                           -2*(r1_x + r_b)*(a11_z - q_z),                                                                                                   -2*r1_y*(a11_z - q_z),                                                                                                                       0, 2*R12*r1_y + 2*R11*(r1_x + r_b), 2*R22*r1_y + 2*R21*(r1_x + r_b), 2*R32*r1_y + 2*R31*(r1_x + r_b)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0, -1,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                               R13,                               R23,                               R33, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                             a21_x - q_x,                                                                                                                     0,                                                                                                                     0,                                                                                                           a21_y - q_y,                                                                                                                       0,                                                                                                                       0,                                                                                                             a21_z - q_z,                            -R13,                            -R23,                            -R33
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0, - 2*R12*r2_y - 2*R11*(r2_x - r_b), - 2*R22*r2_y - 2*R21*(r2_x - r_b), - 2*R32*r2_y - 2*R31*(r2_x - r_b), 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                           -2*(a21_x - q_x)*(r2_x - r_b),                                                                                                   -2*r2_y*(a21_x - q_x),                                                                                                                       0,                                                                                         -2*(a21_y - q_y)*(r2_x - r_b),                                                                                                 -2*r2_y*(a21_y - q_y),                                                                                                                     0,                                                                                           -2*(a21_z - q_z)*(r2_x - r_b),                                                                                                   -2*r2_y*(a21_z - q_z),                                                                                                                       0, 2*R12*r2_y + 2*R11*(r2_x - r_b), 2*R22*r2_y + 2*R21*(r2_x - r_b), 2*R32*r2_y + 2*R31*(r2_x - r_b)
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0, -1,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 1, 0, 0,  0,                                 0,                                 0,                                 0, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0
                       0,             0,  0,                                            0,                                            0,                                            0,                                 0,                                 0,                                 0, 0, 0,  0,                                 0,                                 0,                                 1, 0, 0,  0,               0,               0,               0,               0,    0,    0,    0,                               0, 0,    0,                               0, 0,                                                        0,                                                        0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                                                                                                                     0,                                                                                                                     0,                                                                                                                     0,                                                                                                                       0,                                                                                                                       0,                                                                                                                       0,                               0,                               0,                               0];        
    J2 = zeros(44,36);
    J2(1:32,1:32) = eye(32);
    
    J2(33:41,33:36) =  [  2*q0,  2*q1, -2*q2, -2*q3
                         -2*q3,  2*q2,  2*q1, -2*q0
                          2*q2,  2*q3,  2*q0,  2*q1
                          2*q3,  2*q2,  2*q1,  2*q0
                          2*q0, -2*q1,  2*q2, -2*q3
                         -2*q1, -2*q0,  2*q3,  2*q2
                         -2*q2,  2*q3, -2*q0,  2*q1
                          2*q1,  2*q0,  2*q3,  2*q2
                          2*q0, -2*q1, -2*q2,  2*q3];
    
    J2(42:44,1:3) = h*eye(3);
    
    J3 = zeros(36,32);
    J3(1:32,1:32) = eye(32);
    J3(33:36,4:6) = [ -(h*(q1_o*h^2*w_y^2 - q2_o*w_x*h^2*w_y + q1_o*h^2*w_z^2 - q3_o*w_x*h^2*w_z + 2*q0_o*w_x*h + 4*q1_o))/w_s, -(h*(q2_o*h^2*w_x^2 - q1_o*w_y*h^2*w_x + q2_o*h^2*w_z^2 - q3_o*w_y*h^2*w_z + 2*q0_o*w_y*h + 4*q2_o))/w_s, -(h*(q3_o*h^2*w_x^2 - q1_o*w_z*h^2*w_x + q3_o*h^2*w_y^2 - q2_o*w_z*h^2*w_y + 2*q0_o*w_z*h + 4*q3_o))/w_s
                       (h*(q0_o*h^2*w_y^2 - q3_o*w_x*h^2*w_y + q0_o*h^2*w_z^2 + q2_o*w_x*h^2*w_z - 2*q1_o*w_x*h + 4*q0_o))/w_s,  (h*(q3_o*h^2*w_x^2 - q0_o*w_y*h^2*w_x + q3_o*h^2*w_z^2 + q2_o*w_y*h^2*w_z - 2*q1_o*w_y*h + 4*q3_o))/w_s, -(h*(q2_o*h^2*w_x^2 + q0_o*w_z*h^2*w_x + q2_o*h^2*w_y^2 + q3_o*w_z*h^2*w_y + 2*q1_o*w_z*h + 4*q2_o))/w_s
                      -(h*(q3_o*h^2*w_y^2 + q0_o*w_x*h^2*w_y + q3_o*h^2*w_z^2 + q1_o*w_x*h^2*w_z + 2*q2_o*w_x*h + 4*q3_o))/w_s,  (h*(q0_o*h^2*w_x^2 + q3_o*w_y*h^2*w_x + q0_o*h^2*w_z^2 - q1_o*w_y*h^2*w_z - 2*q2_o*w_y*h + 4*q0_o))/w_s,  (h*(q1_o*h^2*w_x^2 + q3_o*w_z*h^2*w_x + q1_o*h^2*w_y^2 - q0_o*w_z*h^2*w_y - 2*q2_o*w_z*h + 4*q1_o))/w_s
                       (h*(q2_o*h^2*w_y^2 + q1_o*w_x*h^2*w_y + q2_o*h^2*w_z^2 - q0_o*w_x*h^2*w_z - 2*q3_o*w_x*h + 4*q2_o))/w_s, -(h*(q1_o*h^2*w_x^2 + q2_o*w_y*h^2*w_x + q1_o*h^2*w_z^2 + q0_o*w_y*h^2*w_z + 2*q3_o*w_y*h + 4*q1_o))/w_s,  (h*(q0_o*h^2*w_x^2 - q2_o*w_z*h^2*w_x + q0_o*h^2*w_y^2 + q1_o*w_z*h^2*w_y - 2*q3_o*w_z*h + 4*q0_o))/w_s];
    J = J1*J2*J3;
    J = sparse(J);
end
end
