function [F, J, domerr] = mcp_funjac_single_convex_contact_patch_microrobot_inclined(z, jacflag)

%% initialize
z = z(:);
F = [];
J = [];
domerr = 0;

%% obtain value of global variables
global h;

global q_old ;
q_xo = q_old(1);
q_yo = q_old(2);
q_zo = q_old(3);
q0_o = q_old(4);
q1_o = q_old(5);
q2_o = q_old(6);
q3_o = q_old(7);

global nu_old;
v_xo =nu_old(1);
v_yo =nu_old(2);
v_zo =nu_old(3);
w_xo =nu_old(4);
w_yo =nu_old(5);
w_zo =nu_old(6);

global m mu1 mu2 I_xx I_yy I_zz e_o e_r e_t g;

global len wid heg phi theta y_c;

global p_x p_y p_z p_xt p_yt p_zt;

global M_r B F_elect V_m;

global fqn time Van;
%% unknown variables

v_x = z(1);
v_y = z(2);
v_z = z(3);
w_x = z(4);
w_y = z(5);
w_z = z(6);

a11_x = z(7);
a11_y = z(8);
a11_z = z(9);

a12_x = z(10);
a12_y = z(11);
a12_z = z(12);

a21_x = z(13);
a21_y = z(14);
a21_z = z(15);

a22_x = z(16);
a22_y = z(17);
a22_z = z(18);

p1_t = z(19);
p1_o = z(20);
p1_r = z(21);

p2_t = z(22);
p2_o = z(23);
p2_r = z(24);

sig1 = z(25);
sig2 = z(26);

l11 = z(27);
l12 = z(28);
l13 = z(29);
l14 = z(30);
l15 = z(31);
l16 = z(32);
l17 = z(33);

l21 = z(34);
l22 = z(35);
l23 = z(36);
l24 = z(37);
l25 = z(38);
l26 = z(39);
l27 = z(40);


p1_n = z(41);
p2_n = z(42);

%% intermediate variables appear in the chain rule
% z - vector of unknown variables 

% The intermediate variables are:
% 1. [qo(z) q1(z) q2(z) q3(z)] - Quaternions, which depends on z
% 2. Rij(qo,q1,q2,q3) - elements in rotation matrix, which depends on the quaternion
% 3. Iij(qo,q1,q2,q3) - elements in RIR', which depends on the quaternion
% 3. q_x(z),q_y(z),q_z(z) - position vector in l+1, which depends on q_old and z

% Thus system of equations F can be described by the unknown variables z or
% with intermediate variables:
% 1. F(z,Rij,Iij,q_x,q_y,q_z) - F descriabed by z with intermediate variables
% 2. F(z) - F described by unknown variables z

% Based on the chain rule, Jocobain J = J1*J2*J3 where:
% J - dF(z)/dz Jacobian matrix 
% J1 = dF(z,Rij,Iij,q_x,q_y,q_z)/d[z,Rij,q_x,q_y,q_z] 
% J2 = d[z,Rij(qo,q1,q2,q3),Iij(qo,q1,q2,q3),q_x(z),q_y(z),q_z(z)]/d[z,qo,q1,q2,q3] 
% J3 = d[z,qo(z),q1(z),q2(z),q3(z)]/dz 

%% intermediate variables
q0 = -(2*((h*q1_o*w_x)/2 - q0_o + (h*q2_o*w_y)/2 + (h*q3_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q1 = (2*(q1_o + (h*q0_o*w_x)/2 + (h*q3_o*w_y)/2 - (h*q2_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q2 = (2*(q2_o - (h*q3_o*w_x)/2 + (h*q0_o*w_y)/2 + (h*q1_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);
q3 = (2*(q3_o + (h*q2_o*w_x)/2 - (h*q1_o*w_y)/2 + (h*q0_o*w_z)/2))/(h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(1/2);

q_x = q_xo+h*v_x;
q_y = q_yo+h*v_y;
q_z = q_zo+h*v_z;

R11 = q0^2 + q1^2 - q2^2 - q3^2;
R12 = 2*q1*q2 - 2*q0*q3;
R13 = 2*q0*q2 + 2*q1*q3;
R21 = 2*q0*q3 + 2*q1*q2;
R22 = q0^2 - q1^2 + q2^2 - q3^2;
R23 = 2*q2*q3 - 2*q0*q1;
R31 = 2*q1*q3 - 2*q0*q2;
R32 = 2*q0*q1 + 2*q2*q3;
R33 = q0^2 - q1^2 - q2^2 + q3^2;

I11 = I_xx*R11^2 + I_yy*R12^2 + I_zz*R13^2;
I12 = I_xx*R21*R11 + I_yy* R22*R12 + I_zz*R23*R13;
I13 = I_xx*R31*R11 + I_yy* R32*R12 + I_zz*R33*R13;
I21 = I12;
I22 = I_xx*R21^2 + I_yy*R22^2 + I_zz*R23^2;
I23 = I_xx*R31*R21 + I_yy*R32*R22 + I_zz*R33*R23;
I31 = I13;
I32 = I23;
I33 = I_xx*R31^2 + I_yy*R32^2 + I_zz*R33^2;

%% Newton_Euler equations
F(1) = p1_t + p2_t + p_x - m*(v_x - v_xo);
F(2) = p1_o + p_y - m*(v_y - v_yo) + p2_o*cos(theta) + p2_n*sin(theta);
F(3) = p1_n + p_z - F_elect*h - m*(v_z - v_zo) + p2_n*cos(theta) - p2_o*sin(theta) - g*h*m;

F(4) = p_xt - h*(w_yo*(I31*w_xo + I32*w_yo + I33*w_zo) - w_zo*(I21*w_xo + I22*w_yo + I23*w_zo)) - I11*(w_x - w_xo) - I12*(w_y - w_yo) - I13*(w_z - w_zo) + p1_n*(a11_y - q_y) - p1_o*(a11_z - q_z) + p2_n*(cos(theta)*(a21_y - q_y) - sin(theta)*(a21_z - q_z)) - p2_o*(cos(theta)*(a21_z - q_z) + sin(theta)*(a21_y - q_y)) + V_m*h*(B*M_r*cos(2*pi*fqn*time)*(R22*cos(phi) + R23*sin(phi)) + B*M_r*sin(2*pi*fqn*time)*(R32*cos(phi) + R33*sin(phi)));
F(5) = p_yt + h*(w_xo*(I31*w_xo + I32*w_yo + I33*w_zo) - w_zo*(I11*w_xo + I12*w_yo + I13*w_zo)) - I21*(w_x - w_xo) - I22*(w_y - w_yo) - I23*(w_z - w_zo) - p1_n*(a11_x - q_x) + p1_t*(a11_z - q_z) + p2_t*(a21_z - q_z) + p2_r*sin(theta) - p2_n*cos(theta)*(a21_x - q_x) + p2_o*sin(theta)*(a21_x - q_x) - B*M_r*V_m*h*cos(2*pi*fqn*time)*(R12*cos(phi) + R13*sin(phi));
F(6) = p1_r + p_zt - h*(w_xo*(I21*w_xo + I22*w_yo + I23*w_zo) - w_yo*(I11*w_xo + I12*w_yo + I13*w_zo)) - I31*(w_x - w_xo) - I32*(w_y - w_yo) - I33*(w_z - w_zo) + p1_o*(a11_x - q_x) - p1_t*(a11_y - q_y) - p2_t*(a21_y - q_y) + p2_r*cos(theta) + p2_o*cos(theta)*(a21_x - q_x) + p2_n*sin(theta)*(a21_x - q_x) - B*M_r*V_m*h*sin(2*pi*fqn*time)*(R12*cos(phi) + R13*sin(phi));

%% Friction Model without complementarity equation (horizontal surface)

F(7) = p1_t*sig1 + e_t^2*mu1*v_x*(Van + p1_n) - e_t^2*mu1*w_z*(Van + p1_n)*(a11_y - q_y) + e_t^2*mu1*w_y*(Van + p1_n)*(a11_z - q_z);
F(8) = p1_o*sig1 + e_o^2*mu1*v_y*(Van + p1_n) + e_o^2*mu1*w_z*(Van + p1_n)*(a11_x - q_x) - e_o^2*mu1*w_x*(Van + p1_n)*(a11_z - q_z);
F(9) = mu1*w_z*(Van + p1_n)*e_r^2 + p1_r*sig1;

%% Friction Model without complementarity equation (inclined surface)

F(10) = p2_t*sig2 + e_t^2*mu2*(Van + p2_n)*v_x - e_t^2*mu2*(Van + p2_n)*w_z*(a21_y - q_y) + e_t^2*mu2*(Van + p2_n)*w_y*(a21_z - q_z);
F(11) = p2_o*sig2 + e_o^2*mu2*(Van + p2_n)*v_y*cos(theta) - e_o^2*mu2*(Van + p2_n)*v_z*sin(theta) - e_o^2*mu2*(Van + p2_n)*w_x*(cos(theta)*(a21_z - q_z) + sin(theta)*(a21_y - q_y)) + e_o^2*mu2*(Van + p2_n)*w_z*cos(theta)*(a21_x - q_x) + e_o^2*mu2*(Van + p2_n)*w_y*sin(theta)*(a21_x - q_x);
F(12) = p2_r*sig2 + e_r^2*mu2*(Van + p2_n)*w_z*cos(theta) + e_r^2*mu2*(Van + p2_n)*w_y*sin(theta);


%% contact constraints without complementarity equation (cube and horizontal surface)

F(13) = a12_x - a11_x;
F(14) = a12_y - a11_y;
F(15) = a12_z - a11_z + l17;

F(16) = R11*l12 - R11*l11 - R12*l13 + R12*l14 - R13*l15 + R13*l16;
F(17) = R21*l12 - R21*l11 - R22*l13 + R22*l14 - R23*l15 + R23*l16;
F(18) = R31*l12 - R31*l11 - R32*l13 + R32*l14 - R33*l15 + R33*l16 + 1;

%% contact constraints without complementarity equation (cube and inclined surface)

F(19) = a22_x - a21_x;
F(20) = a22_y - a21_y + l27*sin(theta);
F(21) = a22_z - a21_z + l27*cos(theta);

F(22) = R11*l22 - R11*l21 - R12*l23 + R12*l24 - R13*l25 + R13*l26;
F(23) = sin(theta) - R21*l21 + R21*l22 - R22*l23 + R22*l24 - R23*l25 + R23*l26;
F(24) = cos(theta) - R31*l21 + R31*l22 - R32*l23 + R32*l24 - R33*l25 + R33*l26;


%% complementarity equation in Friction Model
F(25) = mu1^2*(p1_n)^2 - p1_r^2/e_r^2 - p1_t^2/e_t^2 - p1_o^2/e_o^2;
F(26) = mu2^2*(Van + p2_n)^2 - p2_r^2/e_r^2 - p2_t^2/e_t^2 - p2_o^2/e_o^2;
%% complementarity equations in contact constraints (cube and horizontal surface)
F(27) = wid/2 + R11*a11_x + R21*a11_y + R31*a11_z - R11*q_x - R21*q_y - R31*q_z;
F(28) = wid/2 - R11*a11_x - R21*a11_y - R31*a11_z + R11*q_x + R21*q_y + R31*q_z;
F(29) = len/2 + R12*a11_x + R22*a11_y + R32*a11_z - R12*q_x - R22*q_y - R32*q_z;
F(30) = len/2 - R12*a11_x - R22*a11_y - R32*a11_z + R12*q_x + R22*q_y + R32*q_z;
F(31) = heg/2 + R13*a11_x + R23*a11_y + R33*a11_z - R13*q_x - R23*q_y - R33*q_z;
F(32) = heg/2 - R13*a11_x - R23*a11_y - R33*a11_z + R13*q_x + R23*q_y + R33*q_z;
F(33) = -a12_z;

%% complementarity equations in contact constraints (cube and inclined surface)
F(34) = wid/2 + R11*a21_x + R21*a21_y + R31*a21_z - R11*q_x - R21*q_y - R31*q_z;
F(35) = wid/2 - R11*a21_x - R21*a21_y - R31*a21_z + R11*q_x + R21*q_y + R31*q_z;
F(36) = len/2 + R12*a21_x + R22*a21_y + R32*a21_z - R12*q_x - R22*q_y - R32*q_z;
F(37) = len/2 - R12*a21_x - R22*a21_y - R32*a21_z + R12*q_x + R22*q_y + R32*q_z;
F(38) = heg/2 + R13*a21_x + R23*a21_y + R33*a21_z - R13*q_x - R23*q_y - R33*q_z;
F(39) = heg/2 - R13*a21_x - R23*a21_y - R33*a21_z + R13*q_x + R23*q_y + R33*q_z;
F(40) = - a22_z*cos(theta) - sin(theta)*(a22_y - y_c);

%% non-penetration 
F(41) = a11_z;
F(42) = a21_z*cos(theta) + sin(theta)*(a21_y - y_c);
%% Jacobian matrix (Using chain rules)

if (jacflag)
    
    J1 = [                     -m,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               1,               0,               0,               1,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                -m,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               1,               0,               0,                                            cos(theta),               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                  sin(theta),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                 -m,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                           -sin(theta),               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         1,                                                                                                                                                                                                  cos(theta),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                          -I11,                                            -I12,                                            -I13,                          0,                        p1_n,                       -p1_o, 0, 0,  0,                                                        0,      p2_n*cos(theta) - p2_o*sin(theta),    - p2_o*cos(theta) - p2_n*sin(theta), 0,           0,           0,               0,     q_z - a11_z,               0,               0, - cos(theta)*(a21_z - q_z) - sin(theta)*(a21_y - q_y),               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                               a11_y - q_y,                                                                                                                                                         cos(theta)*(a21_y - q_y) - sin(theta)*(a21_z - q_z),           0,                                        0,                                        0,           0, B*M_r*V_m*h*cos(phi)*cos(2*pi*fqn*time), B*M_r*V_m*h*sin(phi)*cos(2*pi*fqn*time),           0, B*M_r*V_m*h*cos(phi)*sin(2*pi*fqn*time), B*M_r*V_m*h*sin(phi)*sin(2*pi*fqn*time),   w_xo - w_x,   w_yo - w_y,  w_zo - w_z, h*w_xo*w_zo,  h*w_yo*w_zo,     h*w_zo^2, -h*w_xo*w_yo,   -h*w_yo^2, -h*w_yo*w_zo,                                                         0, p2_o*sin(theta) - p2_n*cos(theta) - p1_n, p1_o + p2_o*cos(theta) + p2_n*sin(theta)
                                0,                                 0,                                  0,                                                                          -I21,                                            -I22,                                            -I23,                      -p1_n,                           0,                        p1_t, 0, 0,  0,                        p2_o*sin(theta) - p2_n*cos(theta),                                      0,                                   p2_t, 0,           0,           0,     a11_z - q_z,               0,               0,     a21_z - q_z,                              sin(theta)*(a21_x - q_x),      sin(theta),    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                               q_x - a11_x,                                                                                                                                                                                   -cos(theta)*(a21_x - q_x),           0, -B*M_r*V_m*h*cos(phi)*cos(2*pi*fqn*time), -B*M_r*V_m*h*sin(phi)*cos(2*pi*fqn*time),           0,                                       0,                                       0,           0,                                       0,                                       0, -h*w_xo*w_zo, -h*w_yo*w_zo,   -h*w_zo^2,  w_xo - w_x,   w_yo - w_y,   w_zo - w_z,     h*w_xo^2, h*w_xo*w_yo,  h*w_xo*w_zo,                  p1_n + p2_n*cos(theta) - p2_o*sin(theta),                                        0,                            - p1_t - p2_t
                                0,                                 0,                                  0,                                                                          -I31,                                            -I32,                                            -I33,                       p1_o,                       -p1_t,                           0, 0, 0,  0,                        p2_o*cos(theta) + p2_n*sin(theta),                                  -p2_t,                                      0, 0,           0,           0,     q_y - a11_y,     a11_x - q_x,               1,     q_y - a21_y,                              cos(theta)*(a21_x - q_x),      cos(theta),    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                    sin(theta)*(a21_x - q_x),           0, -B*M_r*V_m*h*cos(phi)*sin(2*pi*fqn*time), -B*M_r*V_m*h*sin(phi)*sin(2*pi*fqn*time),           0,                                       0,                                       0,           0,                                       0,                                       0,  h*w_xo*w_yo,     h*w_yo^2, h*w_yo*w_zo,   -h*w_xo^2, -h*w_xo*w_yo, -h*w_xo*w_zo,   w_xo - w_x,  w_yo - w_y,   w_zo - w_z,                - p1_o - p2_o*cos(theta) - p2_n*sin(theta),                              p1_t + p2_t,                                        0
           e_t^2*mu1*(Van + p1_n),                                 0,                                  0,                                                                             0,            e_t^2*mu1*(Van + p1_n)*(a11_z - q_z),           -e_t^2*mu1*(Van + p1_n)*(a11_y - q_y),                          0, -e_t^2*mu1*w_z*(Van + p1_n),  e_t^2*mu1*w_y*(Van + p1_n), 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,            sig1,               0,               0,               0,                                                     0,               0, p1_t,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0, e_t^2*mu1*v_x - e_t^2*mu1*w_z*(a11_y - q_y) + e_t^2*mu1*w_y*(a11_z - q_z),                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,               e_t^2*mu1*w_z*(Van + p1_n),              -e_t^2*mu1*w_y*(Van + p1_n)
                                0,            e_o^2*mu1*(Van + p1_n),                                  0,                                         -e_o^2*mu1*(Van + p1_n)*(a11_z - q_z),                                               0,            e_o^2*mu1*(Van + p1_n)*(a11_x - q_x), e_o^2*mu1*w_z*(Van + p1_n),                           0, -e_o^2*mu1*w_x*(Van + p1_n), 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,            sig1,               0,               0,                                                     0,               0, p1_o,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0, e_o^2*mu1*v_y + e_o^2*mu1*w_z*(a11_x - q_x) - e_o^2*mu1*w_x*(a11_z - q_z),                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                               -e_o^2*mu1*w_z*(Van + p1_n),                                        0,               e_o^2*mu1*w_x*(Van + p1_n)
                                0,                                 0,                                  0,                                                                             0,                                               0,                          e_r^2*mu1*(Van + p1_n),                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,            sig1,               0,                                                     0,               0, p1_r,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                             e_r^2*mu1*w_z,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
           e_t^2*mu2*(Van + p2_n),                                 0,                                  0,                                                                             0,            e_t^2*mu2*(Van + p2_n)*(a21_z - q_z),           -e_t^2*mu2*(Van + p2_n)*(a21_y - q_y),                          0,                           0,                           0, 0, 0,  0,                                                        0,            -e_t^2*mu2*w_z*(Van + p2_n),             e_t^2*mu2*w_y*(Van + p2_n), 0,           0,           0,               0,               0,               0,            sig2,                                                     0,               0,    0, p2_t,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                   e_t^2*mu2*v_x - e_t^2*mu2*w_z*(a21_y - q_y) + e_t^2*mu2*w_y*(a21_z - q_z),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,               e_t^2*mu2*w_z*(Van + p2_n),              -e_t^2*mu2*w_y*(Van + p2_n)
                                0, e_o^2*mu2*cos(theta)*(Van + p2_n), -e_o^2*mu2*sin(theta)*(Van + p2_n), -e_o^2*mu2*(cos(theta)*(a21_z - q_z) + sin(theta)*(a21_y - q_y))*(Van + p2_n), e_o^2*mu2*sin(theta)*(Van + p2_n)*(a21_x - q_x), e_o^2*mu2*cos(theta)*(Van + p2_n)*(a21_x - q_x),                          0,                           0,                           0, 0, 0,  0, e_o^2*mu2*(Van + p2_n)*(w_z*cos(theta) + w_y*sin(theta)), -e_o^2*mu2*w_x*sin(theta)*(Van + p2_n), -e_o^2*mu2*w_x*cos(theta)*(Van + p2_n), 0,           0,           0,               0,               0,               0,               0,                                                  sig2,               0,    0, p2_o,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0, e_o^2*mu2*v_y*cos(theta) - e_o^2*mu2*w_x*(cos(theta)*(a21_z - q_z) + sin(theta)*(a21_y - q_y)) - e_o^2*mu2*v_z*sin(theta) + e_o^2*mu2*w_z*cos(theta)*(a21_x - q_x) + e_o^2*mu2*w_y*sin(theta)*(a21_x - q_x),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0, -e_o^2*mu2*(Van + p2_n)*(w_z*cos(theta) + w_y*sin(theta)),    e_o^2*mu2*w_x*sin(theta)*(Van + p2_n),    e_o^2*mu2*w_x*cos(theta)*(Van + p2_n)
                                0,                                 0,                                  0,                                                                             0,               e_r^2*mu2*sin(theta)*(Van + p2_n),               e_r^2*mu2*cos(theta)*(Van + p2_n),                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,            sig2,    0, p2_r,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                 e_r^2*mu2*(w_z*cos(theta) + w_y*sin(theta)),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                         -1,                           0,                           0, 1, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                          -1,                           0, 0, 1,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                          -1, 0, 0,  1,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 1,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0, -R11, R11, -R12, R12, -R13, R13, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,   l12 - l11,                                l14 - l13,                                l16 - l15,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0, -R21, R21, -R22, R22, -R23, R23, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,   l12 - l11,                               l14 - l13,                               l16 - l15,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0, -R31, R31, -R32, R32, -R33, R33, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,   l12 - l11,                               l14 - l13,                               l16 - l15,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                       -1,                                      0,                                      0, 1,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                     -1,                                      0, 0,           1,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0, sin(theta),                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                     -1, 0,           0,           1,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0, cos(theta),                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0, -R11, R11, -R12, R12, -R13, R13,          0,                                                                         0,                                                                                                                                                                                                           0,   l22 - l21,                                l24 - l23,                                l26 - l25,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0, -R21, R21, -R22, R22, -R23, R23,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,   l22 - l21,                               l24 - l23,                               l26 - l25,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0, -R31, R31, -R32, R32, -R33, R33,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,   l22 - l21,                               l24 - l23,                               l26 - l25,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0, -(2*p1_t)/e_t^2, -(2*p1_o)/e_o^2, -(2*p1_r)/e_r^2,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                    mu1^2*(2*Van + 2*p1_n),                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0, -(2*p2_t)/e_t^2,                                       -(2*p2_o)/e_o^2, -(2*p2_r)/e_r^2,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                      mu2^2*(2*Van + 2*p2_n),           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                        R11,                         R21,                         R31, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0, a11_x - q_x,                                        0,                                        0, a11_y - q_y,                                       0,                                       0, a11_z - q_z,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R11,                                     -R21,                                     -R31
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                       -R11,                        -R21,                        -R31, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0, q_x - a11_x,                                        0,                                        0, q_y - a11_y,                                       0,                                       0, q_z - a11_z,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R11,                                      R21,                                      R31
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                        R12,                         R22,                         R32, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                              a11_x - q_x,                                        0,           0,                             a11_y - q_y,                                       0,           0,                             a11_z - q_z,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R12,                                     -R22,                                     -R32
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                       -R12,                        -R22,                        -R32, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                              q_x - a11_x,                                        0,           0,                             q_y - a11_y,                                       0,           0,                             q_z - a11_z,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R12,                                      R22,                                      R32
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                        R13,                         R23,                         R33, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                              a11_x - q_x,           0,                                       0,                             a11_y - q_y,           0,                                       0,                             a11_z - q_z,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R13,                                     -R23,                                     -R33
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                       -R13,                        -R23,                        -R33, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                              q_x - a11_x,           0,                                       0,                             q_y - a11_y,           0,                                       0,                             q_z - a11_z,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R13,                                      R23,                                      R33
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0, -1,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                      R11,                                    R21,                                    R31, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0, a21_x - q_x,                                        0,                                        0, a21_y - q_y,                                       0,                                       0, a21_z - q_z,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R11,                                     -R21,                                     -R31
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                     -R11,                                   -R21,                                   -R31, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0, q_x - a21_x,                                        0,                                        0, q_y - a21_y,                                       0,                                       0, q_z - a21_z,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R11,                                      R21,                                      R31
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                      R12,                                    R22,                                    R32, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                              a21_x - q_x,                                        0,           0,                             a21_y - q_y,                                       0,           0,                             a21_z - q_z,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R12,                                     -R22,                                     -R32
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                     -R12,                                   -R22,                                   -R32, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                              q_x - a21_x,                                        0,           0,                             q_y - a21_y,                                       0,           0,                             q_z - a21_z,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R12,                                      R22,                                      R32
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                      R13,                                    R23,                                    R33, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                              a21_x - q_x,           0,                                       0,                             a21_y - q_y,           0,                                       0,                             a21_z - q_z,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                      -R13,                                     -R23,                                     -R33
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                     -R13,                                   -R23,                                   -R33, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                              q_x - a21_x,           0,                                       0,                             q_y - a21_y,           0,                                       0,                             q_z - a21_z,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                       R13,                                      R23,                                      R33
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                                      0,                                      0, 0, -sin(theta), -cos(theta),               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           1, 0, 0,  0,                                                        0,                                      0,                                      0, 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0
                                0,                                 0,                                  0,                                                                             0,                                               0,                                               0,                          0,                           0,                           0, 0, 0,  0,                                                        0,                             sin(theta),                             cos(theta), 0,           0,           0,               0,               0,               0,               0,                                                     0,               0,    0,    0,    0,   0,    0,   0,    0,   0, 0,    0,   0,    0,   0,    0,   0,          0,                                                                         0,                                                                                                                                                                                                           0,           0,                                        0,                                        0,           0,                                       0,                                       0,           0,                                       0,                                       0,            0,            0,           0,           0,            0,            0,            0,           0,            0,                                                         0,                                        0,                                        0];
    
    J2 = zeros(63,46);
    J2(1:42,1:42) = eye(42); %dz/dz
    J2(43:51,end-3:end) = [2*q0,  2*q1, -2*q2, -2*q3
                          -2*q3,  2*q2,  2*q1, -2*q0
                           2*q2,  2*q3,  2*q0,  2*q1
                           2*q3,  2*q2,  2*q1,  2*q0
                           2*q0, -2*q1,  2*q2, -2*q3
                          -2*q1, -2*q0,  2*q3,  2*q2
                          -2*q2,  2*q3, -2*q0,  2*q1
                           2*q1,  2*q0,  2*q3,  2*q2
                           2*q0, -2*q1, -2*q2,  2*q3]; %dRij/d[q0,q1,q2,q3]
                       
    J2(52:60,end-3:end) = [                                                 4*I_xx*R11*q0 - 4*I_yy*R12*q3 + 4*I_zz*R13*q2,                                                 4*I_xx*R11*q1 + 4*I_yy*R12*q2 + 4*I_zz*R13*q3,                                                 4*I_yy*R12*q1 - 4*I_xx*R11*q2 + 4*I_zz*R13*q0,                                                 4*I_zz*R13*q1 - 4*I_yy*R12*q0 - 4*I_xx*R11*q3
                            2*I_xx*R11*q3 + 2*I_xx*R21*q0 + 2*I_yy*R12*q0 - 2*I_yy*R22*q3 - 2*I_zz*R13*q1 + 2*I_zz*R23*q2, 2*I_xx*R11*q2 + 2*I_xx*R21*q1 - 2*I_yy*R12*q1 + 2*I_yy*R22*q2 - 2*I_zz*R13*q0 + 2*I_zz*R23*q3, 2*I_xx*R11*q1 - 2*I_xx*R21*q2 + 2*I_yy*R12*q2 + 2*I_yy*R22*q1 + 2*I_zz*R13*q3 + 2*I_zz*R23*q0, 2*I_xx*R11*q0 - 2*I_xx*R21*q3 - 2*I_yy*R12*q3 - 2*I_yy*R22*q0 + 2*I_zz*R13*q2 + 2*I_zz*R23*q1
                            2*I_xx*R31*q0 - 2*I_xx*R11*q2 + 2*I_yy*R12*q1 - 2*I_yy*R32*q3 + 2*I_zz*R13*q0 + 2*I_zz*R33*q2, 2*I_xx*R11*q3 + 2*I_xx*R31*q1 + 2*I_yy*R12*q0 + 2*I_yy*R32*q2 - 2*I_zz*R13*q1 + 2*I_zz*R33*q3, 2*I_yy*R12*q3 - 2*I_xx*R31*q2 - 2*I_xx*R11*q0 + 2*I_yy*R32*q1 - 2*I_zz*R13*q2 + 2*I_zz*R33*q0, 2*I_xx*R11*q1 - 2*I_xx*R31*q3 + 2*I_yy*R12*q2 - 2*I_yy*R32*q0 + 2*I_zz*R13*q3 + 2*I_zz*R33*q1
                            2*I_xx*R11*q3 + 2*I_xx*R21*q0 + 2*I_yy*R12*q0 - 2*I_yy*R22*q3 - 2*I_zz*R13*q1 + 2*I_zz*R23*q2, 2*I_xx*R11*q2 + 2*I_xx*R21*q1 - 2*I_yy*R12*q1 + 2*I_yy*R22*q2 - 2*I_zz*R13*q0 + 2*I_zz*R23*q3, 2*I_xx*R11*q1 - 2*I_xx*R21*q2 + 2*I_yy*R12*q2 + 2*I_yy*R22*q1 + 2*I_zz*R13*q3 + 2*I_zz*R23*q0, 2*I_xx*R11*q0 - 2*I_xx*R21*q3 - 2*I_yy*R12*q3 - 2*I_yy*R22*q0 + 2*I_zz*R13*q2 + 2*I_zz*R23*q1
                                                                            4*I_xx*R21*q3 + 4*I_yy*R22*q0 - 4*I_zz*R23*q1,                                                 4*I_xx*R21*q2 - 4*I_yy*R22*q1 - 4*I_zz*R23*q0,                                                 4*I_xx*R21*q1 + 4*I_yy*R22*q2 + 4*I_zz*R23*q3,                                                 4*I_xx*R21*q0 - 4*I_yy*R22*q3 + 4*I_zz*R23*q2
                            2*I_xx*R31*q3 - 2*I_xx*R21*q2 + 2*I_yy*R22*q1 + 2*I_yy*R32*q0 + 2*I_zz*R23*q0 - 2*I_zz*R33*q1, 2*I_xx*R21*q3 + 2*I_xx*R31*q2 + 2*I_yy*R22*q0 - 2*I_yy*R32*q1 - 2*I_zz*R23*q1 - 2*I_zz*R33*q0, 2*I_xx*R31*q1 - 2*I_xx*R21*q0 + 2*I_yy*R22*q3 + 2*I_yy*R32*q2 - 2*I_zz*R23*q2 + 2*I_zz*R33*q3, 2*I_xx*R21*q1 + 2*I_xx*R31*q0 + 2*I_yy*R22*q2 - 2*I_yy*R32*q3 + 2*I_zz*R23*q3 + 2*I_zz*R33*q2
                            2*I_xx*R31*q0 - 2*I_xx*R11*q2 + 2*I_yy*R12*q1 - 2*I_yy*R32*q3 + 2*I_zz*R13*q0 + 2*I_zz*R33*q2, 2*I_xx*R11*q3 + 2*I_xx*R31*q1 + 2*I_yy*R12*q0 + 2*I_yy*R32*q2 - 2*I_zz*R13*q1 + 2*I_zz*R33*q3, 2*I_yy*R12*q3 - 2*I_xx*R31*q2 - 2*I_xx*R11*q0 + 2*I_yy*R32*q1 - 2*I_zz*R13*q2 + 2*I_zz*R33*q0, 2*I_xx*R11*q1 - 2*I_xx*R31*q3 + 2*I_yy*R12*q2 - 2*I_yy*R32*q0 + 2*I_zz*R13*q3 + 2*I_zz*R33*q1
                            2*I_xx*R31*q3 - 2*I_xx*R21*q2 + 2*I_yy*R22*q1 + 2*I_yy*R32*q0 + 2*I_zz*R23*q0 - 2*I_zz*R33*q1, 2*I_xx*R21*q3 + 2*I_xx*R31*q2 + 2*I_yy*R22*q0 - 2*I_yy*R32*q1 - 2*I_zz*R23*q1 - 2*I_zz*R33*q0, 2*I_xx*R31*q1 - 2*I_xx*R21*q0 + 2*I_yy*R22*q3 + 2*I_yy*R32*q2 - 2*I_zz*R23*q2 + 2*I_zz*R33*q3, 2*I_xx*R21*q1 + 2*I_xx*R31*q0 + 2*I_yy*R22*q2 - 2*I_yy*R32*q3 + 2*I_zz*R23*q3 + 2*I_zz*R33*q2
                                                                            4*I_yy*R32*q1 - 4*I_xx*R31*q2 + 4*I_zz*R33*q0,                                                 4*I_xx*R31*q3 + 4*I_yy*R32*q0 - 4*I_zz*R33*q1,                                                 4*I_yy*R32*q3 - 4*I_xx*R31*q0 - 4*I_zz*R33*q2,                                                 4*I_xx*R31*q1 + 4*I_yy*R32*q2 + 4*I_zz*R33*q3];
 
    %dIij/d[q0,q1,q2,q3]                                                                    
    J2(61:63,1:3) = h*eye(3);                   
    
    J3 = zeros(46:42);  
    J3(1:42,1:42) = eye(42);  %dz/dz
    N_J3 = (h^2*w_x^2 + h^2*w_y^2 + h^2*w_z^2 + 4)^(3/2);
    J3(43:46,4:6) = [ -(h*(q1_o*h^2*w_y^2 - q2_o*w_x*h^2*w_y + q1_o*h^2*w_z^2 - q3_o*w_x*h^2*w_z + 2*q0_o*w_x*h + 4*q1_o))/N_J3, -(h*(q2_o*h^2*w_x^2 - q1_o*w_y*h^2*w_x + q2_o*h^2*w_z^2 - q3_o*w_y*h^2*w_z + 2*q0_o*w_y*h + 4*q2_o))/N_J3, -(h*(q3_o*h^2*w_x^2 - q1_o*w_z*h^2*w_x + q3_o*h^2*w_y^2 - q2_o*w_z*h^2*w_y + 2*q0_o*w_z*h + 4*q3_o))/N_J3
                       (h*(q0_o*h^2*w_y^2 - q3_o*w_x*h^2*w_y + q0_o*h^2*w_z^2 + q2_o*w_x*h^2*w_z - 2*q1_o*w_x*h + 4*q0_o))/N_J3,  (h*(q3_o*h^2*w_x^2 - q0_o*w_y*h^2*w_x + q3_o*h^2*w_z^2 + q2_o*w_y*h^2*w_z - 2*q1_o*w_y*h + 4*q3_o))/N_J3, -(h*(q2_o*h^2*w_x^2 + q0_o*w_z*h^2*w_x + q2_o*h^2*w_y^2 + q3_o*w_z*h^2*w_y + 2*q1_o*w_z*h + 4*q2_o))/N_J3
                      -(h*(q3_o*h^2*w_y^2 + q0_o*w_x*h^2*w_y + q3_o*h^2*w_z^2 + q1_o*w_x*h^2*w_z + 2*q2_o*w_x*h + 4*q3_o))/N_J3,  (h*(q0_o*h^2*w_x^2 + q3_o*w_y*h^2*w_x + q0_o*h^2*w_z^2 - q1_o*w_y*h^2*w_z - 2*q2_o*w_y*h + 4*q0_o))/N_J3,  (h*(q1_o*h^2*w_x^2 + q3_o*w_z*h^2*w_x + q1_o*h^2*w_y^2 - q0_o*w_z*h^2*w_y - 2*q2_o*w_z*h + 4*q1_o))/N_J3
                       (h*(q2_o*h^2*w_y^2 + q1_o*w_x*h^2*w_y + q2_o*h^2*w_z^2 - q0_o*w_x*h^2*w_z - 2*q3_o*w_x*h + 4*q2_o))/N_J3, -(h*(q1_o*h^2*w_x^2 + q2_o*w_y*h^2*w_x + q1_o*h^2*w_z^2 + q0_o*w_y*h^2*w_z + 2*q3_o*w_y*h + 4*q1_o))/N_J3,  (h*(q0_o*h^2*w_x^2 - q2_o*w_z*h^2*w_x + q0_o*h^2*w_y^2 + q1_o*w_z*h^2*w_y - 2*q3_o*w_z*h + 4*q0_o))/N_J3];%d(q0 q1 q2 q3)/d(wx wy wz)
 
    J = J1*J2*J3;
    J = sparse(J);
    
end
end
